package mx.com.liverpool.p360.services.core.temp.characteristic;

import mx.com.liverpool.p360.services.core.RESTWrapper;
import mx.com.liverpool.p360.services.core.RequestHandler;

public class ActualizaNombresEs {

	private static final RESTWrapper rw = new RESTWrapper();
	
	public static void main(String[] args) {
		java.util.Map<String, String> qp = new java.util.TreeMap<>();
		RequestHandler rh = new RequestHandler(new org.json.JSONArray().put(new org.json.JSONObject().put("identifier", "CharacteristicLang.Name(es)")), 1000, response -> {
			rw.writeData("list", "Characteristic", null, qp, response, System.out::println);
		});
		String[] pieces = null;
		for(String pair : PAIRS) {
			pieces = pair.split("\t");
			if(pieces.length > 1 && pieces[1] != null && !pieces[1].isEmpty())
				rh.addRow(new org.json.JSONObject().put("object", new org.json.JSONObject().put("id", "'" + pieces[0] + "'")).put("values", new org.json.JSONArray().put(pieces[1])));
		}
		rh.sendData();
	}
	
	private static final String[] PAIRS = ("EmpastadoVaD	Empastado\r\n"
			+ "AlturaDeLaLlamaVaD	Altura de la llama\r\n"
			+ "SAPCapacidadDeAlmacenamientoVaD	Capacidad del congelador\r\n"
			+ "IndicadorCambioDeFiltroVaD	Indicador cambio de filtro\r\n"
			+ "NumeroDeDiscosVaD	Número de discos\r\n"
			+ "PresenciadecafeinaVaD	Presencia de cafeina\r\n"
			+ "DetalleVaD	Detalles\r\n"
			+ "CompartimentoparacalzadoVaD	Compartimento para calzado\r\n"
			+ "ConvertibleComoCunaVaD	Convertible como cuna\r\n"
			+ "IngredienteadicionalVaD	Ingrediente adicional\r\n"
			+ "AnguloDeEscaneoVaD	Ángulo de escaneo\r\n"
			+ "CaracteristicasEspecialesVaD	Características especiales\r\n"
			+ "EjerciciosPosiblesVaD	Ejercicios Posibles\r\n"
			+ "IntervaloDeCambioRecomendadoVaD	Intervalo de cambio recomendado\r\n"
			+ "AE375	Instrucciones de cuidado\r\n"
			+ "ColorImpresionVaD	Color impresion\r\n"
			+ "AE488	Largo de manga\r\n"
			+ "VelocidadDeConteoVaD	Velocidad de conteo\r\n"
			+ "ContenidoDeSolucionVaD	Contenido de solución\r\n"
			+ "TipodeescapeVaD	Tipo de escape\r\n"
			+ "NiveladoresVaD	Niveladores\r\n"
			+ "RemovibleconacetonaVaD	Removible con acetona\r\n"
			+ "TecnologiaDelColchonVaD	Tecnología del colchón\r\n"
			+ "LargoDeLaCorreaVaD	Largo de la correa\r\n"
			+ "InteligenciaartificialintegradaVaD	Inteligencia artificial integrada\r\n"
			+ "TiempoDeEvaporacionVaD	Tiempo de evaporación\r\n"
			+ "PersonalizableVaD	Personalizable\r\n"
			+ "DiametroDelNucleoDelRolloVaD	Diametro Del Nucleo Del Rollo\r\n"
			+ "CambiadorIntegradoVaD	Cambiador integrado\r\n"
			+ "EfectoDeNieveVaD	Efecto de nieve\r\n"
			+ "MaterialDeSuelaVaD	Material de la suela\r\n"
			+ "AspectoTapeteVaD	Aspecto tapete\r\n"
			+ "RelacionaspectoVaD	Relación aspecto\r\n"
			+ "AltoVaD	Alto del producto\r\n"
			+ "TipodeinstalacionVaD	Tipo de instalacion\r\n"
			+ "GarantiaDelFabricanteVaD	Garantía del fabricante\r\n"
			+ "EspacioentrenivelesVaD	Espacio entre niveles\r\n"
			+ "TipoDeMedicamentoVaD	Tipo de medicamento\r\n"
			+ "PortalapizVaD	Portalapiz\r\n"
			+ "ResistenciaalpillingVaD	Resistencia al pilling\r\n"
			+ "DeshumidificadorVaD	Deshumidificador\r\n"
			+ "AnguloDeDeteccionVerticalVaD	Angulo de detección vertical\r\n"
			+ "NumeroDeCuerdasVaD	Número de cuerdas\r\n"
			+ "ParteVaD	Parte\r\n"
			+ "TipodedosificacionVaD	Tipo de dosificacion\r\n"
			+ "TipodepuntadaVaD	Tipo de puntada\r\n"
			+ "ParadaDeEmergenciaVaD	Parada De Emergencia\r\n"
			+ "EspacioFlexibleVaD	Espacio flexible\r\n"
			+ "RequieretomadeaguaVaD	Requiere toma de agua\r\n"
			+ "BeneficiosDeLaCeraVaD	Beneficios de la cera\r\n"
			+ "TipoDeCharolaVaD	Tipo de charola\r\n"
			+ "TipoDeMagnesioVaD	Tipo de magnesio\r\n"
			+ "RelacionDeMezclaVaD	Relacion de mezcla\r\n"
			+ "NumerodeusuariosVaD	Número de usuarios\r\n"
			+ "RangomedicionVaD	Rango medición\r\n"
			+ "TamanoDeLaValvulaVaD	Tamaño de la valvula\r\n"
			+ "TamanoDeParticulasVaD	Tamaño de partículas\r\n"
			+ "RangoDeMedicionVaD	Rango de medición\r\n"
			+ "CompatibilidadDeMonitorVaD	Compatibilidad de monitor\r\n"
			+ "EsAntihumedadKVaD	Es antihumedad\r\n"
			+ "MangoVaD	Mango\r\n"
			+ "GROES	Cantidad de Piezas\r\n"
			+ "ConexiondeaguaVaD	Conexion de agua\r\n"
			+ "CompatibilidadDelSeparadorVaD	Compatibilidad del separador\r\n"
			+ "NumeroDeMonitoresSoportadosVaD	Número de monitores soportados\r\n"
			+ "PanelableVaD	Panelable\r\n"
			+ "TipodemarcadorVaD	Tipo de marcador\r\n"
			+ "AcompanamientoautomaticoVaD	Acompañamiento automático\r\n"
			+ "CompatibilidadDelFilamentoVaD	Compatibilidad del filamento\r\n"
			+ "DiapasonVaD	Material del diapasón\r\n"
			+ "ConsistenciamasaVaD	Consistencia masa\r\n"
			+ "FiltroDeLuzAzulVaD	Filtro de luz azul\r\n"
			+ "AnejamientoVaD	Añejamiento\r\n"
			+ "ResistenciaAIntemperieVaD	Resistencia a intemperie\r\n"
			+ "TipoDeArenaCompatibleVaD	Tipo de arena compatible\r\n"
			+ "AE453	Tecnología inverter\r\n"
			+ "IntegracionconotrasaplicacionesVaD	Integracion con otras aplicaciones\r\n"
			+ "LongitudDelHiloVaD	Longitud del hilo\r\n"
			+ "AE448	Fábrica de hielos\r\n"
			+ "MapasIntegradosVaD	Mapas Integrados\r\n"
			+ "CompartimentosEnLaPuertaVaD	Compartimentos en la puerta\r\n"
			+ "ProteccioncontraimpactoslateralesVaD	Proteccion contra impactos laterales\r\n"
			+ "FuenteDeEnergiaVaD	Fuente de energía\r\n"
			+ "IncluyefotografiasVaD	Incluye fotografias\r\n"
			+ "AE446	Despachador de agua\r\n"
			+ "AE447	Despachador de hielos\r\n"
			+ "NecesidadesDeLuzVaD	Necesidades de luz\r\n"
			+ "BordesDeLaMesaVaD	Bordes de la mesa\r\n"
			+ "BotonDeInicio/ParadaVaD	Botón de inicio/parada\r\n"
			+ "NumberOfDoorsAtt	Número de puertas\r\n"
			+ "PrecorteVaD	Precorte\r\n"
			+ "ModosDeTraduccionVaD	Modos de traducción\r\n"
			+ "FacilidaddealmacenamientoVaD	Facilidad de almacenamiento\r\n"
			+ "CaducidadVaD	Caducidad\r\n"
			+ "KilatajeVaD	Kilataje\r\n"
			+ "MaternidadYLactanciaVaD	Maternidad y lactancia\r\n"
			+ "TipodeedulcoranteVaD	Tipo de edulcorante\r\n"
			+ "TipoDeJuegoVaD	Tipo De Juego\r\n"
			+ "AdicionvitaminasVaD	Adicion vitaminas\r\n"
			+ "EsDesinfectanteKVaD	Es desinfectante\r\n"
			+ "TipodepeliculacompatibleVaD	Tipo de pelicula compatible\r\n"
			+ "BiodegradabilidadVaD	Biodegradabilidad\r\n"
			+ "ClasificacionACEAVaD	Clasificacion acea\r\n"
			+ "DuracionDelJuegoVaD	Duración del juego\r\n"
			+ "TipoDePlanVaD	Tipo de plan\r\n"
			+ "AccesoalcompartimentoprincipalVaD	Acceso al compartimento principal\r\n"
			+ "SePuedeInflarConVaD	Se puede inflar con\r\n"
			+ "PropiedadprotectoraVaD	Propiedad protectora\r\n"
			+ "AccionAireCalienteYFrioKVaD	Acción aire caliente y frío\r\n"
			+ "MecanismoDesagueVaD	Mecanismo desague\r\n"
			+ "AnchoDelRolloVaD	Ancho del rollo\r\n"
			+ "DeteccionDeArritmiasVaD	Detección de arritmias\r\n"
			+ "AislamientoDeMovimientoVaD	Aislamiento de movimiento\r\n"
			+ "RanurasexpansionVaD	Ranuras expansion\r\n"
			+ "BolsillosVaD	Bolsillos\r\n"
			+ "EditorialVaD	Editorial\r\n"
			+ "SensorestactilesVaD	Sensores tactiles\r\n"
			+ "TipodeborradoVaD	Tipo de borrado\r\n"
			+ "TapaIntegradaVaD	Tapa integrada\r\n"
			+ "TipoDeZapatoVaD	Tecnología de calzado\r\n"
			+ "PuertaReversibleVaD	Puerta reversible\r\n"
			+ "MaterialdiapasonVaD	Material diapason\r\n"
			+ "ControldeplagasVaD	Control de plagas\r\n"
			+ "DistribuciondelafibraVaD	Distribucion de la fibra\r\n"
			+ "LimpiadorDeLenguaVaD	Limpiador de lengua\r\n"
			+ "ColorDelHumoVaD	Color del humo\r\n"
			+ "DiametroDelFilamentoVaD	Diámetro del filamento\r\n"
			+ "CapacidadDeHerramientasVaD	Capacidad De Herramientas\r\n"
			+ "RetardanteAlFuegoVaD	Retardante al fuego\r\n"
			+ "DisenoDeLasEmpunadurasVaD	Diseño de las empunaduras\r\n"
			+ "MecanismodebloqueoVaD	Mecanismo de bloqueo\r\n"
			+ "FuncionanticalcareaVaD	Funcion anticalcarea\r\n"
			+ "UsoRecomendadoKVaD	Capacidad compatible\r\n"
			+ "TipodetinacompatibleVaD	Tipo de tina compatible\r\n"
			+ "RangodepresionVaD	Rango de presion\r\n"
			+ "FormatodispositivoVaD	Formato dispositivo\r\n"
			+ "TipodedispensadorVaD	Tipo de dispensador\r\n"
			+ "CorreadepechoVaD	Correa de pecho\r\n"
			+ "DistribuciondenutrientesVaD	Distribucion de nutrientes\r\n"
			+ "TiempoDeCuradoVaD	Tiempo de curado\r\n"
			+ "ApoyabrazosAjustableVaD	Apoyabrazos ajustable\r\n"
			+ "ResistenciaALaOxidacionVaD	Resistencia a la oxidación\r\n"
			+ "Anti-FrizzVaD	Anti-frizz\r\n"
			+ "ModosDeLuzVaD	Modos de luz\r\n"
			+ "TipodeaislamientotermicoVaD	Tipo de aislamiento termico\r\n"
			+ "LargoDelRolloVaD	Largo del rollo\r\n"
			+ "MaridajesugeridoVaD	Maridaje sugerido\r\n"
			+ "TipodeazucarVaD	Tipo de azucar\r\n"
			+ "TipoDeAnclajeVaD	Tipo de anclaje\r\n"
			+ "EfectosDeSonidoVaD	Efectos de sonido\r\n"
			+ "EstanteslateralesVaD	Estantes laterales\r\n"
			+ "IncluyeMacetaVaD	Incluye maceta\r\n"
			+ "ConfundaprotectoraVaD	Con funda protectora\r\n"
			+ "GuiasDeCorteVaD	Guias de corte\r\n"
			+ "AlimentosrecomendadosVaD	Alimentos recomendados\r\n"
			+ "DenominacionNutricionalVaD	Denominación nutricional\r\n"
			+ "FormatoderesultadoVaD	Formato de resultado\r\n"
			+ "CantidadDeFocosQueIncluyeVaD	Cantidad de focos que incluye\r\n"
			+ "ConcucharaVaD	Con cuchara\r\n"
			+ "BrujulaVaD	Brujula\r\n"
			+ "MaterialDelMastilVaD	Material del mástil\r\n"
			+ "TecnologiaIAVaD	Tecnologia IA\r\n"
			+ "VersiondehdmiVaD	Version de HDMI\r\n"
			+ "SimVaD	SIM\r\n"
			+ "ApoyapiesAjustableVaD	Apoyapiés ajustable\r\n"
			+ "AE424	Fácil limpieza\r\n"
			+ "AnguloDeDeteccionHorizontalVaD	Angulo de detección horizontal\r\n"
			+ "FuerzaMaximaDeSujecionVaD	Fuerza Maxima De Sujecion\r\n"
			+ "MaterialAtt	Material\r\n"
			+ "CantidadDeColoresVaD	Cantidad De Colores\r\n"
			+ "CaracteristicaDeAlimentosVaD	Característica de alimentos\r\n"
			+ "EsSetAntiacneKVaD	Velocidad del ventilador\r\n"
			+ "ResistenciaAAltasTemperaturasVaD	Resistencia a altas temperaturas\r\n"
			+ "FormacalizVaD	Forma caliz\r\n"
			+ "CompartimientosParaDerrameVaD	Compartimentos para derrame\r\n"
			+ "ConfigurableOrder	Orden de atributos producto configurable\r\n"
			+ "ProfundidadDePerforacionVaD	Profundidad de perforación\r\n"
			+ "NeckAtt	Cuello\r\n"
			+ "ControlDeOloresVaD	Control de olores\r\n"
			+ "BloqueodeteclawindowsVaD	Bloqueo de tecla windows\r\n"
			+ "AdhesionALaCamaVaD	Adhesion a la cama\r\n"
			+ "AppCompatibleVAD	App compatible\r\n"
			+ "AnchoVaD	Ancho del producto\r\n"
			+ "SinBpaVaD	Esfera lentes de contacto\r\n"
			+ "ResistenciaalcloroVaD	Resistencia al cloro\r\n"
			+ "TexturaVaD	Textura\r\n"
			+ "HueveraVaD	Huevera\r\n"
			+ "ResistenteAManchasVaD	Resistente a manchas\r\n"
			+ "IdiomasVaD	Idiomas\r\n"
			+ "LargoDeLaPestanaVaD	Largo de la pestaña\r\n"
			+ "ConSistemaAnticolicosVaD	Con sistema anticolicos\r\n"
			+ "PuertosvideoVaD	Puertos video\r\n"
			+ "ControlDeHumedadVaD	Control de humedad\r\n"
			+ "NumeroDeSoportesVaD	Número de soportes\r\n"
			+ "TipoDeBaseVaD	Zona de soporte\r\n"
			+ "CapacidadDeClasificacionVaD	Capacidad de clasificación\r\n"
			+ "IndicadaparaVaD	Indicada para\r\n"
			+ "CompatibilidadconamplificadorexternoVaD	Compatibilidad con amplificador externo\r\n"
			+ "NumeroDeRegistrosVaD	Número de registros\r\n"
			+ "CaracteristicasDelCaballeteVaD	Caracteristicas del caballete\r\n"
			+ "FormaVaD	Forma\r\n"
			+ "TipoDeEstructuraVaD	Tipo de pisada\r\n"
			+ "ProteccionparacamaraVaD	Protección para cámara\r\n"
			+ "DisenoTematicoVaD	Diseño temático\r\n"
			+ "AnchoDeLaCorreaVaD	Ancho de la correa\r\n"
			+ "EnhebradorautomaticoVaD	Enhebrador automatico\r\n"
			+ "DepositoDesmontableVaD	Depósito desmontable\r\n"
			+ "TipodemandrilVaD	Tipo de mandril\r\n"
			+ "TipodeAgaveVaD	Tipo de agave\r\n"
			+ "PuertaVaD	Puerta de acceso rápido\r\n"
			+ "PrecaucionesVaD	Precauciones\r\n"
			+ "TipodeenfriamientoVaD	Tipo de enfriamiento\r\n"
			+ "APruebaDeAguaVaD	A prueba de agua\r\n"
			+ "TipoDePeineVaD	Tipo de peine\r\n"
			+ "UsoInteriorExterior VaD	Uso\r\n"
			+ "ConbaneraintegradaVaD	Con banera integrada\r\n"
			+ "EsterilVaD	Estéril\r\n"
			+ "TipoDePrendaInferiorVaD	Tipo de prenda inferior\r\n"
			+ "FormadeltableroVaD	Forma del tablero\r\n"
			+ "TipodeproduccionVaD	Tipo de produccion\r\n"
			+ "EfectoDeAguaVaD	Efecto de agua\r\n"
			+ "CortadorpastillasVaD	Cortador pastillas\r\n"
			+ "BeneficiosDeUsoVaD	Beneficios de uso\r\n"
			+ "ParaAltoKilometrajeVaD	Para alto kilometraje\r\n"
			+ "ControlDeTemperaturaVaD	Control de temperatura\r\n"
			+ "TiroDelPantalonVaD	Tiro del pantalón\r\n"
			+ "AutonomiaDeBateriaVaD	Autonomía de batería\r\n"
			+ "CortedehiloautomaticoVaD	Corte de hilo automatico\r\n"
			+ "CompartimentosParaFreirVaD	Compartimentos para freír\r\n"
			+ "AreaDeCoberturaVaD	Área de cobertura\r\n"
			+ "AE501	Servicio confort\r\n"
			+ "TipoDeAgarreVaD	Tipo de agarre\r\n"
			+ "BolsillosadicionalesVaD	Bolsillos adicionales\r\n"
			+ "ComodidaddeusoVaD	Comodidad de uso\r\n"
			+ "VelocidaddegrabadoVaD	Velocidad de grabado\r\n"
			+ "PuertosusbfrontalesVaD	Puertos usb frontales\r\n"
			+ "TipodeguitarraVaD	Tipo de guitarra\r\n"
			+ "AdaptadorincluidoVaD	Adaptador incluido\r\n"
			+ "FormaplacamadreVaD	Forma placa madre\r\n"
			+ "TipoDePantalonVaD	Tipo de pantalón\r\n"
			+ "VelocidadDeImpactoVaD	Velocidad De Impacto\r\n"
			+ "Tecnologia2VaD	Tecnología\r\n"
			+ "VersionjugadorVaD	Version jugador\r\n"
			+ "NivelDeDificultadVaD	Nivel de dificultad\r\n"
			+ "AprobacionesOEMVaD	Aprobaciones oem\r\n"
			+ "MemoriademarcacionrapidaVaD	Memoria de marcacion rapida\r\n"
			+ "UbicacionrecomendadaVaD	Ubicacion recomendada\r\n"
			+ "TipoDeSujecionVaD	Tipo de sujeción\r\n"
			+ "RequiereBateriaVaD	Requiere batería\r\n"
			+ "ProfundidadDelProductoVaD	Profundidad del producto\r\n"
			+ "CierreAutomaticoVaD	Cierre automático\r\n"
			+ "AtrilparapartiturasVaD	Atril para partituras\r\n"
			+ "CalefaccionVaD	Calefacción\r\n"
			+ "AlarmaDeDeteccionDePecesVaD	Alarma de deteccion de peces\r\n"
			+ "AditivosVaD	Aditivos\r\n"
			+ "CantidadDeHojasVaD	Cantidad de hojas\r\n"
			+ "TipoDePaloVaD	Tipo de palo\r\n"
			+ "MaterialDeLasEmpunadurasVaD	Material De Las Empunaduras\r\n"
			+ "CaracteristicasAdicionalesVaD	Caracteristicas Adicionales\r\n"
			+ "FiltroDeAguaVaD	Filtro de agua\r\n"
			+ "MaterialDeLaClavijaVaD	Material de la clavija\r\n"
			+ "AgarreVaD	Agarre\r\n"
			+ "BeneficiosSaludablesVaD	Beneficios saludables\r\n"
			+ "CompatibilidadConLaCamaVaD	Compatibilidad con la cama\r\n"
			+ "TiempoDeRespuestaVaD	Tiempo de respuesta\r\n"
			+ "CompatibilidadconfundasVaD	Compatibilidad con fundas\r\n"
			+ "TamanoDelBolsilloVaD	Tamaño del bolsillo\r\n"
			+ "NumeroDePaginasVaD	Número de páginas\r\n"
			+ "DosisDeNicotinaVaD	Dosis de nicotina\r\n"
			+ "AccesoriosqueincluyelaconsolaVaD	Accesorios que incluye la consola\r\n"
			+ "GenderAtt	Género\r\n"
			+ "VPNcompatibleVaD	VPN compatible\r\n"
			+ "IndicadorDeEstadoVaD	Indicador de estado\r\n"
			+ "NumeroDeCajonesVaD	Número de cajones\r\n"
			+ "MezclaVaD	Mezcla\r\n"
			+ "ReposacabezaAjustableVaD	Reposacabeza ajustable\r\n"
			+ "RespuestadebajosVaD	Respuesta de bajos\r\n"
			+ "AdaptabilidadfacialVaD	Adaptabilidad facial\r\n"
			+ "EmpunaduraadicionalVaD	Empunadura adicional\r\n"
			+ "CapuchaVaD	Capucha\r\n"
			+ "TipodehieloVaD	Tipo de hielo\r\n"
			+ "Textura	Textura\r\n"
			+ "AdaptadorParaCocheVaD	Adaptador para coche\r\n"
			+ "CoberturadecanasVaD	Cobertura de canas\r\n"
			+ "ResistenciaALasManchasVaD	Resistencia a las manchas\r\n"
			+ "EspacioParaCopasVaD	Espacio para copas\r\n"
			+ "LargoDelBrazoVaD	Largo del brazo\r\n"
			+ "AperturaVaD	Apertura\r\n"
			+ "AnchollantaVaD	Ancho llanta\r\n"
			+ "DiametroDeLaPerforacionVaD	Diámetro de la perforación\r\n"
			+ "SaldoVaD	Saldo\r\n"
			+ "TipoDeConjuntoVaD	Tipo de conjunto\r\n"
			+ "MaterialDeCajonesVaD	Material de cajones\r\n"
			+ "AnguloDeDeteccionVaD	Ángulo de detección\r\n"
			+ "IncluyepedestalVaD	Incluye pedestal\r\n"
			+ "MetodoDeBombeoVaD	Método de bombeo\r\n"
			+ "EstabilidadVaD	Estabilidad\r\n"
			+ "AlimentadorautomaticodocumentosVaD	Alimentador automatico documentos\r\n"
			+ "LegFitAtt	Fit\r\n"
			+ "ContenidodesalVaD	Contenido de sal\r\n"
			+ "RecuentoVaD	Recuento\r\n"
			+ "MecanismodeelevacionVaD	Mecanismo de elevacion\r\n"
			+ "FormadelacestaVaD	Forma de la cesta\r\n"
			+ "ColorDelDiamanteVaD	Color del diamante\r\n"
			+ "CapacidadDeAlmacenamientoDeAguaVaD	Capacidad de almacenamiento de agua\r\n"
			+ "MetododeborradoVaD	Metodo de borrado\r\n"
			+ "TipoDeBarandalVaD	Tipo de barandal\r\n"
			+ "ProfundidadDeAlcanceVaD	Profundidad de alcance\r\n"
			+ "CapotaVaD	Capota\r\n"
			+ "CinturonDeSeguridadVaD	Cinturón de seguridad\r\n"
			+ "ResistenciaDelRolloVaD	Resistencia del rollo\r\n"
			+ "TipodepuertaVaD	Tipo de puerta\r\n"
			+ "FuncionesAvanzadasVaD	Funciones avanzadas\r\n"
			+ "FormatoVaD	Formato\r\n"
			+ "IluminacionRgbVaD	Iluminacion RGB\r\n"
			+ "MemoriaDeMedicionVaD	Memoria de medición\r\n"
			+ "PurezaDiamanteVaD	Pureza diamante\r\n"
			+ "TipodecableVaD	Tipo de cable\r\n"
			+ "ProfundidaddeinstalacionVaD	Profundidad de instalacion\r\n"
			+ "SAPTipoDeAlmacenamientoVaD	Tipo de almacenamiento\r\n"
			+ "ErgonomiaVaD	Ergonomia\r\n"
			+ "SubzonavitivinicolaVaD	Sub zona vitivinicola\r\n"
			+ "RequiereFiltroVaD	Requiere filtro\r\n"
			+ "TipoDelTecladoVaD	Tipo del teclado\r\n"
			+ "VersionamientoVaD	Versionamiento\r\n"
			+ "BrilloAutomaticoVaD	Brillo automático\r\n"
			+ "TipoDeUkuleleVaD	Tipo de ukelele\r\n"
			+ "TiposDeMonedasAdmitidasVaD	Tipos de monedas admitidas\r\n"
			+ "ActivacionRequeridaVaD	Activacion Requerida\r\n"
			+ "NumeroDeTrucosVaD	Número de trucos\r\n"
			+ "AnoDelCalendarioVaD	Año del calendario\r\n"
			+ "TranspirabilidadVaD	Transpirabilidad\r\n"
			+ "FormaDeLaCabezaVaD	Forma de la cabeza\r\n"
			+ "CategoriaVaD	Categoría\r\n"
			+ "UsoMedicamentosVaD	Uso medicamentos\r\n"
			+ "CompatibilidadconasadoresVaD	Compatibilidad con asadores\r\n"
			+ "AdherenciaVaD	Adherencia\r\n"
			+ "DenominacionZonadeorigenVaD	Denominacion Zona de origen\r\n"
			+ "FuncionderetrocesoVaD	Funcion de retroceso\r\n"
			+ "EsgiratorioVaD	Es giratorio\r\n"
			+ "IndicadorDeSobrecalentamientoVaD	Indicador de sobrecalentamiento\r\n"
			+ "VelocidadSinCargaVaD	Velocidad sin carga\r\n"
			+ "MaterialDelCuerpoVaD	Material del cuerpo\r\n"
			+ "NumeroDeMechasVaD	Número de mechas\r\n"
			+ "TipoDeTrucosVaD	Tipo de trucos\r\n"
			+ "IntensidadDeLuzVaD	Intensidad De Luz\r\n"
			+ "TipodeojalVaD	Tipo de ojal\r\n"
			+ "ElevaciondelsueloVaD	Elevacion del suelo\r\n"
			+ "FormadelcableVaD	Forma del cable\r\n"
			+ "TipoDeCristalVaD	Tipo de cristal\r\n"
			+ "BeneficiosDeLaCremaVaD	Beneficios de la crema\r\n"
			+ "ResistenciaAlVientoVaD	Resistencia al viento\r\n"
			+ "AutorVaD	Autor\r\n"
			+ "Resistencia al calor	Resistencia al calor\r\n"
			+ "IncluyekitdereparacionVaD	Incluye kit de reparacion\r\n"
			+ "CierreVaD	Cierre\r\n"
			+ "RegulacionDeIntensidadVaD	Regulación de intensidad\r\n"
			+ "TipoDeUltrasonidoVaD	Tipo de ultrasonido\r\n"
			+ "RequiereRiegoVaD	Requiere riego\r\n"
			+ "AntighostingVaD	Anti ghosting\r\n"
			+ "IncluyejuegosVaD	Incluye juegos\r\n"
			+ "MaterialDeCharolasVaD	Material de charolas\r\n"
			+ "TipoDeRodamientoVaD	Tipo de rodamiento\r\n"
			+ "ConvertibleComoCamaVaD	Convertible como cama\r\n"
			+ "DistanciaMaximaDeDeteccionVaD	Distancia máxima de detección\r\n"
			+ "TemperaturaDeOperacionVaD	Temperatura De Operacion\r\n"
			+ "SilbatoDeEmergenciaVaD	Silbato de emergencia\r\n"
			+ "TipoDeAroVaD	Tipo de aro\r\n"
			+ "BandejaDeGoteoExtraibleVaD	Bandeja de goteo extraible\r\n"
			+ "CertificacionesVaD	Certificaciones\r\n"
			+ "EmisionDeSonidosVaD	Emisión de sonidos\r\n"
			+ "CompatibilidadconaccesoriosVaD	Compatibilidad con accesorios\r\n"
			+ "PosicionamientodeagujaVaD	Posicionamiento de aguja\r\n"
			+ "LubricacionVaD	Lubricacion\r\n"
			+ "RequiereinfladocontinuoVaD	Requiere inflado continuo\r\n"
			+ "TipodepianoVaD	Tipo de piano\r\n"
			+ "NumerodetrastesVaD	Numero de trastes\r\n"
			+ "TipoDeTableroVaD	Tipo De Tablero\r\n"
			+ "BaseAntideslizanteVaD	Base antideslizante\r\n"
			+ "GarantiaVaD	Garantía del producto\r\n"
			+ "TipoDeDoselVaD	Tipo de dosel\r\n"
			+ "MaterialDeTetinaVaD	Material de tetina\r\n"
			+ "NumeroDePatasVaD	Número de patas\r\n"
			+ "TipodeafeitadoraVaD	Tipo de afeitadora\r\n"
			+ "BolsilloparabotellaVaD	Bolsillo para botella\r\n"
			+ "PatternAtt	Estampado\r\n"
			+ "TipodecocinacompatibleVaD	Tipo de cocina compatible\r\n"
			+ "BordesdeseguridadVaD	Bordes de seguridad\r\n"
			+ "EfectoDePestanasVaD	Efecto de pestañas\r\n"
			+ "DisolucionVaD	Disolucion\r\n"
			+ "CantidadDeFocosRequeridosVaD	Cantidad de focos requeridos\r\n"
			+ "TextosVaD	Textos\r\n"
			+ "FiloVaD	Filo\r\n"
			+ "EncendidoLineaBlancaVaD	Encendido linea blanca\r\n"
			+ "TipoDePlasticoVaD	Tipo de plástico\r\n"
			+ "TipodeaceiteVaD	Tipo de aceite\r\n"
			+ "NumeroquemadoresVaD	Número quemadores\r\n"
			+ "MedicionesVaD	Mediciones\r\n"
			+ "TipodeimanVaD	Tipo de iman\r\n"
			+ "GradosdedeclinacionVaD	Grados de declinación\r\n"
			+ "IncluyecapabarberoVaD	Incluye capa barbero\r\n"
			+ "AsientoGiratorioVaD	Asiento giratorio\r\n"
			+ "IncluyetecladoVaD	Incluye teclado\r\n"
			+ "ActualizacionesautomaticasVaD	Actualizaciones automaticas\r\n"
			+ "TipodeblindajeVaD	Tipo de blindaje\r\n"
			+ "DeteccionDeMonedasFalsasVaD	Detección de monedas falsas\r\n"
			+ "TemperaturaDeImpresionVaD	Temperatura de impresión\r\n"
			+ "ProductoOrganicoKVaD	Producto orgánico\r\n"
			+ "SensibilidadVaD	Sensibilidad\r\n"
			+ "CopiadoraVaD	Copiadora\r\n"
			+ "QuilatajeDiamanteVaD	Quilataje diamante\r\n"
			+ "FlagImportBySS	Flag Import por SS\r\n"
			+ "TiempodeproduccionporcicloVaD	Tiempo de produccion por ciclo\r\n"
			+ "TamanoDeLaMuestraVaD	Tamaño de la muestra\r\n"
			+ "CapacidadDeConteoVaD	Capacidad de conteo\r\n"
			+ "MaterialDeLaCorreaVaD	Material De La Correa\r\n"
			+ "PresenciadefrutossecosVaD	Presencia de frutos secos\r\n"
			+ "CompartimentoparatarjetasVaD	Compartimento para tarjetas\r\n"
			+ "AlivioDePresionVaD	Alivio de presion\r\n"
			+ "ElaboracionVaD	Elaboracion\r\n"
			+ "PermeabilidadAlOxigenoVaD	Permeabilidad al oxígeno\r\n"
			+ "EstucheIncluidoVaD	Estuche incluido\r\n"
			+ "ResistenciaALaCorrosionVaD	Resistencia a la corrosión\r\n"
			+ "IluminacionEnCongeladorVaD	Iluminación en congelador\r\n"
			+ "IsbnVaD	ISBN\r\n"
			+ "AumentoDelEspejoVaD	Aumento del espejo\r\n"
			+ "MoliendaVaD	Molienda\r\n"
			+ "SoporteparamarcadoresVaD	Soporte para marcadores\r\n"
			+ "PotenciadesuccionVaD	Potencia de succion\r\n"
			+ "InformacionenpantallaVaD	Informacion en pantalla\r\n"
			+ "NumberOf PiecesAtt	Número de piezas\r\n"
			+ "NumerodecavidadesVaD	Número de cavidades\r\n"
			+ "TecnologiadelavadoVaD	Tecnologia de lavado\r\n"
			+ "IncluyeescaleraVaD	Incluye escalera\r\n"
			+ "AjustedepastillasVaD	Ajuste de pastillas\r\n"
			+ "AlmohadillareemplazableVaD	Almohadilla reemplazable\r\n"
			+ "TipodeescrituraVaD	Tipo de escritura\r\n"
			+ "ConcentracioncloroactivoVaD	Concentracion cloro activo\r\n"
			+ "NiveldeproteccionVaD	Nivel de proteccion\r\n"
			+ "MetodosDeIdentificacionVaD	Métodos de identificación\r\n"
			+ "CharolaPortaGisVaD	Número de charolas\r\n"
			+ "PuentenasalajustableVaD	Puente nasal ajustable\r\n"
			+ "FlujoDeAireVaD	Flujo de aire\r\n"
			+ "NumerodetinasVaD	Numero de tinas\r\n"
			+ "NivelesDeAlturaVaD	Niveles de altura\r\n"
			+ "CompatibilidadconhumidificadorVaD	Compatibilidad con humidificador\r\n"
			+ "CorteDelDiamanteVaD	Corte del diamante\r\n"
			+ "TapaVaD	Tapa\r\n"
			+ "IncluyemouseVaD	Incluye mouse\r\n"
			+ "PortavasosVaD	Portavasos\r\n"
			+ "AlarmaDePuertaVaD	Alarma de puerta\r\n"
			+ "TipoDeBrochaVaD	Tipo de brocha\r\n"
			+ "TipoDeLedVaD	Tipo de led\r\n"
			+ "ColorDelMarcoVaD	Color del marco\r\n"
			+ "DurabilidaddelasteclasVaD	Durabilidad de las teclas\r\n"
			+ "TipodebobinaVaD	Tipo de bobina\r\n"
			+ "DesechableVaD	Desechable\r\n"
			+ "SoporteLumbarVaD	Soporte lumbar\r\n"
			+ "GeneroliterarioVaD	Género literario\r\n"
			+ "PublicoRecomendadoVaD	Público recomendado\r\n"
			+ "TipoestucheVaD	Tipo estuche\r\n"
			+ "DistanciaEntreAgujerosVaD	Distancia entre agujeros\r\n"
			+ "AnguloVaD	Angulo\r\n"
			+ "AccesosinconexionVaD	Acceso sin conexion\r\n"
			+ "IndicedecargaVaD	Índice de carga\r\n"
			+ "InstruccionesdecuidadoVaD	Instrucciones de cuidado\r\n"
			+ "VelocidaddecorteVaD	Velocidad de corte\r\n"
			+ "FormadeltanqueVaD	Forma del tanque\r\n"
			+ "TamanoArmadoVaD	Tamaño armado\r\n"
			+ "ColorDeLaCorreaVaD	Color de la correa\r\n"
			+ "CertificacionVaD	Certificación\r\n"
			+ "TiempoDeProteccionVaD	Tiempo de protección\r\n"
			+ "FurnitureFeaturesAtt	Característica especial\r\n"
			+ "ExcipientesVaD	Excipientes\r\n"
			+ "EstructuraVaD	Estructura\r\n"
			+ "IndicadorDeReemplazoDeFiltroVaD	Indicador de reemplazo de filtro\r\n"
			+ "FunciondecongelacionrapidaVaD	Funcion de congelacion rapida\r\n"
			+ "MetododerizadoVaD	Metodo de rizado\r\n"
			+ "GradoAlimenticioVaD	Grado alimenticio\r\n"
			+ "TemporizadorVaD	Temporizador\r\n"
			+ "TransparenciaVaD	Transparencia\r\n"
			+ "TipodepizarronVaD	Tipo de pizarron\r\n"
			+ "VelocidadMinimaDeFuncionamientoVaD	Velocidad Minima De Funcionamiento").split("\r\n");
	
}
