select LAST_RUN_ID, MANDATORY_SYNC_STATUS, MANDATORY_STATUS,
       count(*) PRODUCTS, min(MANDATORY_PCT) MIN_PCT, max(MANDATORY_PCT) MAX_PCT
from P360_EXPLOIT.TB_COMPLETENESS_SNAPSHOT
group by LAST_RUN_ID,MANDATORY_SYNC_STATUS,MANDATORY_STATUS;

select count(*) INVALID_METRICS from P360_EXPLOIT.TB_COMPLETENESS_SNAPSHOT
where MANDATORY_TOTAL != MANDATORY_PRESENT + MANDATORY_MISSING
   or MANDATORY_PCT < 0 or MANDATORY_PCT > 100
   or MANDATORY_PRESENT < 0 or MANDATORY_MISSING < 0;

select count(*) PENDING_WORK_ROWS from P360_EXPLOIT.TT_PRODUCT_COMPLETENESS_WORK;
