package mx.com.liverpool.p360.services.core;
import org.json.*;import java.util.*;
public class NativeModelPriorityTest {
 static int n;static void check(boolean b){n++;if(!b)throw new AssertionError("check "+n);}
 static JSONObject record(String key,Object value){return new JSONObject().put("_qualification",new JSONObject().put("characteristic",new JSONObject().put("_code",key))).put("_recordLang",new JSONArray().put(new JSONObject().put("values",new JSONArray().put(value))));}
 static String value(JSONObject data,String key){JSONArray a=data.getJSONArray("_characteristicRecords");for(int i=0;i<a.length();i++){JSONObject r=a.getJSONObject(i);if(key.equals(r.getJSONObject("_qualification").getJSONObject("characteristic").getString("_code")))return r.getJSONArray("_recordLang").getJSONObject(0).getJSONArray("values").getString(0);}return "";}
 public static void main(String[] args)throws Exception {
 JSONObject d=new JSONObject("{sku:123,gtin:'001234',lang:[{_qualification:{language:{_code:'esl'}},descriptionShort:'N',productName:'PN',descriptionLong:'Long',descriptionLong2:'Long2'}],articleExtraData:[{_qualification:{targetMarket:{_code:'MX'}},tamanoUnico:{_label:' ',_code:'M'},coloursLiverpoolAtt:{_label:'Blue'},supplierPartNumber:'Native SP',sapObjectType:{_label:'Native type'}}]}");
 JSONArray records=new JSONArray();for(String k:new String[]{"SKU","MainBarCodeS4H","TamanoUnico","ColoursLiverpoolAtt","SupplierPartNumber","SAPObjectType","DescriptionLong","DescriptionLong2","Name","ProductName"})records.put(record(k,"old"));d.put("_characteristicRecords",records);
 NativeNamePriority.apply(new JSONObject().put("_data",d));
 for(String[] pair:new String[][]{{"SKU","123"},{"MainBarCodeS4H","001234"},{"TamanoUnico","M"},{"ColoursLiverpoolAtt","Blue"},{"SupplierPartNumber","Native SP"},{"SAPObjectType","Native type"},{"DescriptionLong","Long"},{"DescriptionLong2","Long2"},{"Name","N"},{"ProductName","PN"}})check(value(d,pair[0]).equals(pair[1]));
 JSONObject out=new JSONObject("{SKU:'request',MainBarCodeS4H:'old',header:{SKU:'stale'},attributes:{DescriptionLong:'old'}}");NativeModelPriority.finish(out,d,false);check(out.getString("SKU").equals("123"));check(out.getJSONObject("header").getString("SKU").equals("123"));check(out.getString("MainBarCodeS4H").equals("001234"));check(!out.has("MainBarCode"));check(out.getString("TamanoUnico").equals("M"));
 JSONObject empty=new JSONObject("{sku:null,gtin:' ',lang:[{_qualification:{language:{_code:'esl'}},descriptionLong:''}],articleExtraData:[{_qualification:{targetMarket:{_code:'MX'}},supplierPartNumber:' '}]}");empty.put("_characteristicRecords",new JSONArray().put(record("SKU","fallback")).put(record("DescriptionLong","fallback text")));NativeModelPriority.prepare(new JSONObject().put("_data",empty));check(value(empty,"SKU").equals("fallback"));check(value(empty,"DescriptionLong").equals("fallback text"));check(!empty.has("gtin"));check(!empty.getJSONArray("lang").getJSONObject(0).has("descriptionLong"));
 JSONObject product=new JSONObject("{detail:{Res_Int_02:999,EAN:'00999',Res_Text2G_02:'web'},languages:[{LanguageID:10,DescriptionLong:'native text'}],domains:[{EntityID:21006,Res_Text250_01:'model',lookups:{Std_Int_10:{Code:'123',Name:'Supplier'},Res_Int_08:{Name:'Individual'}}}]}");
 JSONObject article=new JSONObject("{detail:{Res_Int_02:77,EAN:'0077'},domains:[{EntityID:21106,lookups:{Res_Int_01:{Code:'L'},Res_Int_02:{Name:'Red'}}}]}");JSONObject response=new JSONObject("{header:{SKU:'request',MainBarCode:'old'},basicData:{DescriptionLong:'stale'},attributes:{DescriptionLong:'stale'},variants:[{variantId:'v',SKU:'old',TamanoUnico:'old',ColoursLiverpoolAtt:'old'}]}");
 NativeModelPriority.finishProduct(response,product,Collections.singletonMap("v",article));check(response.getJSONObject("header").getString("SKU").equals("999"));check(response.getJSONObject("header").getString("MainBarCode").equals("00999"));check(response.getString("supplier").equals("00000000000000000123"));check(response.getJSONObject("basicData").getString("DescriptionLong").equals("native text"));check(response.getJSONObject("attributes").getString("DescriptionLong").equals("native text"));JSONObject v=response.getJSONArray("variants").getJSONObject(0);check(v.getString("SKU").equals("77"));check(v.getString("TamanoUnico").equals("L"));check(v.getString("ColoursLiverpoolAtt").equals("Red"));
 String before=response.toString();NativeModelPriority.finishProduct(response,product,Collections.singletonMap("v",article));check(before.equals(response.toString()));
 Class.forName("mx.com.liverpool.p360.services.core.GetProposals",false,NativeModelPriorityTest.class.getClassLoader()).getDeclaredMethods();System.out.println("PASS "+n+" model-priority checks and GetProposals JVM verification");
 }
}
