CREATE TABLE P360_EXPLOIT.TB_MANDATORY_COMP_PENDING (
  ENTITY_TYPE VARCHAR2(20 BYTE) NOT NULL,
  ENTITY_IDENTIFIER NVARCHAR2(255) NOT NULL,
  CHANGE_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  FORCE_RECALC NUMBER(1) DEFAULT 1 NOT NULL,
  CHARACTERISTICS VARCHAR2(4000 BYTE) DEFAULT '[]' NOT NULL,
  PAGE_CURSOR NUMBER(19) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  NEXT_ATTEMPT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
  LAST_ERROR VARCHAR2(1000 BYTE),
  CONSTRAINT PK_MANDATORY_COMP_PENDING PRIMARY KEY (ENTITY_TYPE, ENTITY_IDENTIFIER)
    USING INDEX TABLESPACE P360_EXPLOIT_INDEX,
  CONSTRAINT CK_MC_PENDING_ENTITY CHECK (ENTITY_TYPE IN ('Product2G','Article','Metadata')),
  CONSTRAINT CK_MC_PENDING_FORCE CHECK (FORCE_RECALC IN (0,1))
) TABLESPACE P360_EXPLOIT_DATA;
CREATE INDEX P360_EXPLOIT.IX_MC_PENDING_DUE ON P360_EXPLOIT.TB_MANDATORY_COMP_PENDING
  (NEXT_ATTEMPT, CREATED_AT) TABLESPACE P360_EXPLOIT_INDEX;
CREATE TABLE P360_EXPLOIT.TB_MANDATORY_COMP_CONTROL (
  ID NUMBER(1) NOT NULL,
  PENDING_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  MAX_PENDING NUMBER(10) DEFAULT 100000 NOT NULL,
  CONSTRAINT PK_MANDATORY_COMP_CONTROL PRIMARY KEY (ID)
    USING INDEX TABLESPACE P360_EXPLOIT_INDEX,
  CONSTRAINT CK_MC_CONTROL_ID CHECK (ID IN (1,2)),
  CONSTRAINT CK_MC_CONTROL_CAP CHECK (PENDING_COUNT >= 0 AND MAX_PENDING BETWEEN 1 AND 100000)
) TABLESPACE P360_EXPLOIT_DATA;
INSERT INTO P360_EXPLOIT.TB_MANDATORY_COMP_CONTROL (ID) VALUES (1);
INSERT INTO P360_EXPLOIT.TB_MANDATORY_COMP_CONTROL (ID) VALUES (2);
